### ISSUE TITLE
(display...) prints twice

### ISSUE THREAD

**Issue by schanzer** [ds26gte/code.pyret.org#21]
`(display "moo")`, when run, should only print "moo" once. Instead, it prints it twice.

**Comment by ds26gte** [comment]
Fixed in 3341250 and ds26gte/pyret-lang@def4880.

(Also, when wrapping prints around values evaluated in the definitions window, skip for "nothing" values. (display/print of nothing will return something by intent.))

**Comment by schanzer** [comment]
I'm still seeing "nothing" get printed, though the issue itself has now been resolved. I'll open a separate issue to track "nothings".
